set -g allow-passthrough

set -g base-index 1
setw -g pane-base-index 1
set-option -g renumber-windows on

# Enable vi motions
setw -g mode-keys vi

# Visual selection like Vim
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line

# Copy like Vim (yank)
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "pbcopy"

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

bind-key x kill-pane

# tmux sessionizer
bind-key -r f run-shell "tmux neww ~/.local/scripts/tmux-sessionizer"
bind-key -r k run-shell "~/.local/scripts/tmux-sessionizer ~/projects/work/tmux-theme"

