#!/bin/sh

# custom
sudo dnf install golang git jj neovim

# rust - first check if rustup is installed, if not install install
if ! command -v rustup &> /dev/null
then 
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
fi

# luavim
sudo dnf install make pip python npm node cargo ripgrep
# lazygit
sudo dnf copr enable atim/lazygit
sudo dnf install lazygit
# install - first check if lunarvim is installed, if not install install
if ! command -v lvim &> /dev/null
then
  LV_BRANCH='release-1.4/neovim-0.9' bash <(curl -s https://raw.githubusercontent.com/LunarVim/LunarVim/release-1.4/neovim-0.9/utils/installer/install.sh)
fi
