#!/bin/sh

# custom
sudo dnf install golang git jj neovim

# luavim
sudo dnf install make pip python npm node cargo ripgrep
# lazygit
sudo dnf copr enable atim/lazygit
sudo dnf install lazygit
# install
LV_BRANCH='release-1.4/neovim-0.9' bash <(curl -s https://raw.githubusercontent.com/LunarVim/LunarVim/release-1.4/neovim-0.9/utils/installer/install.sh)
