-- lua/plugins/copilot.lua
return {
  --   {
  --     "zbirenbaum/copilot.lua",
  --     keys = {
  --       {
  --         "<leader>at",
  --         function()
  --           if require("copilot.client").is_disabled() then
  --             require("copilot.command").enable()
  --           else
  --             require("copilot.command").disable()
  --           end
  --         end,
  --         desc = "Toggle (Copilot)",
  --       },
  --     },
  --     opts = {
  --       panel = {
  --         auto_refresh = false,
  --         keymap = {
  --           accept = "<CR>",
  --           jump_prev = "[[",
  --           jump_next = "]]",
  --           refresh = "gr",
  --           open = "<M-CR>",
  --         },
  --       },
  --       suggestion = {
  --         auto_trigger = true,
  --         keymap = {
  --           accept = "<C-l>",
  --           prev = "<M-[>",
  --           next = "<M-]>",
  --           dismiss = "<C-]>",
  --         },
  --       },
  --     },
  --   },
}
